# Generated by Django 5.2.3 on 2025-08-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPCSectionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('mapped_category', models.CharField(max_length=100)),
                ('punishment', models.TextField()),
                ('bailability_status', models.CharField(max_length=50)),
                ('court_jurisdiction', models.CharField(max_length=100)),
                ('full_legal_text', models.TextField()),
            ],
            options={
                'db_table': 'ipc_sections',
            },
        ),
    ]
