# Generated by Django 5.2.3 on 2025-08-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPCSectionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=50, unique=True, verbose_name='Section Number')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('mapped_category', models.CharField(max_length=100, verbose_name='Category')),
                ('punishment', models.TextField(verbose_name='Punishment')),
                ('bailability_status', models.CharField(max_length=50, verbose_name='Bailability Status')),
                ('court_jurisdiction', models.CharField(max_length=100, verbose_name='Court Jurisdiction')),
                ('full_legal_text', models.TextField(verbose_name='Full Legal Text')),
                ('urgency_label', models.CharField(max_length=50, verbose_name='Urgency Label')),
                ('keywords', models.TextField(verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'IPC Section',
                'verbose_name_plural': 'IPC Sections',
                'db_table': 'ipc_sections',
            },
        ),
    ]
